app:
  scheduler:
    enable: true
    interval: 20000
    force-check-delay: 10000
spring:
  liquibase:
    enabled: false
  datasource:
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/scrapper"
    username: "postgres"
    password: "postgres"
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: "/swagger-ui"

logging:
  config: classpath:log4j2-plain.xml

github:
  token: ${GITHUB_TOKEN}
  url: "https://api.github.com"

stackoverflow:
  url: "https://api.stackexchange.com"

bot:
  url: "http://localhost:8090"
